language: node_js
cache: yarn
install: yarn
jobs:
  include:
    - stage: Unit tests
      node_js:
        - 8
        - 6
      install: yarn
      script: npm test
    - stage: Release
      node_js: 8
      script: npm run semantic-release-ci
