version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.16.1
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

  unit_tests:
    docker:
      - image: circleci/node:8.16.1
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Unit tests
          command: npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - unit_tests:
          requires:
            - build
