version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
          - npm-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - npm-dependencies-
      - run:
          name: Install dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: npm-dependencies-{{ checksum "package.json" }}

  unit_tests:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Unit tests
          command: npm test

  deploy:
    docker:
      - image: circleci/node:8.11.3
    steps:
      - checkout
      - restore_cache:
          key: npm-dependencies-{{ checksum "package.json" }}
      - run:
          name: Semantic release
          command: npm run semantic-release


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          filters:
            tags:
              ignore: /^v\d+\.\d+\.\d+$/
      - unit_tests:
          requires:
            - build
          filters:
            tags:
              ignore: /^v\d+\.\d+\.\d+$/
      - deploy:
          requires:
            - unit_tests
          filters:
            branches:
              only: master
            tags:
              ignore: /.*/
